---
apiVersion: v1
kind: Namespace
metadata:
  name: security
---
apiVersion: v1
kind: Namespace
metadata:
  name: traefik
---
apiVersion: v1
kind: Namespace
metadata:
  name: rev-proxy
---
apiVersion: v1
kind: Namespace
metadata:
  name: otus-user