configuration:
  clientID: otus-service-user
  clientSecret: gHJJskTluHrSMF0NUwtdnKT3qehO838O
  cookieSecret: djhMb0lUK3FnMmFOQjdwOWsxMmsyb0VZcUxpZTNiZWg=
  oidcIssuerUrl: http://keycloak.security/realms/otus