---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: otus-user
  name: otus-service-user-api
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
    - host: arch.homework
      http:
        paths:
          - backend:
              service:
                name: otus-service-user
                port:
                  name: http
            pathType: Prefix
            path: /api/user(/|$)(.*)