---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: otus-service-user-prp
  namespace: otus-user
spec:
  replacePathRegex:
    regex: ^/api/user(/|$)(.*)
    replacement: /$2
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: otus-service-user
  namespace: otus-user
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`arch.homework`) && PathPrefix(`/api/user`)
      kind: Rule
      middlewares:
        - name: otus-service-user-prp
          namespace: otus-user
      services:
        - name: otus-service-user
          namespace: otus-user
          port: 80