---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: otus-user
  name: otus-service-user
  labels:
    app.kubernetes.io/name: otus-service-user
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: otus-service-user
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: otus-service-user
    spec:
      containers:
        - name: otus-service-user
          image: auwerk/otus-service-user:v1.0.6
          env:
            - name: OTUS_KEYCLOAK_URL
              value: http://keycloak.security
            - name: OTUS_KEYCLOAK_REALM
              value: otus
            - name: OTUS_POSTGRES_HOST
              value: postgresql.otus-user
            - name: OTUS_KEYCLOAK_CLIENT_ID
              value: otus-service-user
            - name: OTUS_KEYCLOAK_CLIENT_SECRET
              value: gHJJskTluHrSMF0NUwtdnKT3qehO838O
            - name: OTUS_USER_PUBLIC_PATH
              value: /api/user
          ports:
            - name: web
              containerPort: 8080
      initContainers:
        - name: otus-service-user-db
          image: auwerk/otus-service-user-db:v1.0.1
          command: [ 'sh', '-c', 'liquibase --defaultsFile=/liquibase/changelog/liquibase.properties update' ]
---
apiVersion: v1
kind: Service
metadata:
  namespace: otus-user
  name: otus-service-user
  labels:
    app.kubernetes.io/name: otus-service-user
spec:
  selector:
    app.kubernetes.io/name: otus-service-user
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      name: http